export const HCI_UNIFIED_SCHEMA_V1 = {
  metadata: {
    schemaVersion: '1.0',
    nativeLanguage: 'en',
    translations: ['pt-BR'],
    generatedAt: null,
    generatedBy: 'ADMIN_WEB',
    storageMode: 'UNIFIED_SQL',
    tenantId: null,
    licenseId: null,
  },

  dictionaries: {
    sessionType: ['TRAINING', 'SIMULATION', 'COMPETITION'],
    modality: ['PISTOL', 'RIFLE'],
    sessionStatus: ['PENDING_REVIEW', 'APPROVED', 'ARCHIVED', 'DELETED'],
    sourceType: [
      'LOGIN_APP',
      'ADMIN_REACT',
      'MANUAL_ADMIN',
      'HCI_IA_IMPORTED_REVIEW',
      'TARGETSCAN_ADMIN',
      'RECOVERED_DB_MERGE',
      'AUDIT_INCOMPLETE',
    ],
    directionCodePistol: [
      'CENTER',
      'UP',
      'UPPER_RIGHT',
      'RIGHT',
      'LOWER_RIGHT',
      'DOWN',
      'LOWER_LEFT',
      'LEFT',
      'UPPER_LEFT',
    ],
    directionCodeRifle: ['CENTER', 'Q1', 'Q2', 'Q3', 'Q4'],
  },

  entities: {
    athlete: {
      athleteId: 'string',
      athleteName: 'string',
      athleteEmail: 'string|null',
      modality: 'PISTOL|RIFLE|null',
      levelCode: 'string|null',
      sourceType: 'string',
      createdAt: 'timestamp',
      updatedAt: 'timestamp',
    },

    sessionHeader: {
      sessionId: 'string',
      athleteId: 'string',
      athleteName: 'string',
      eventCode: 'string',
      sessionType: 'TRAINING|SIMULATION|COMPETITION',
      modality: 'PISTOL|RIFLE',
      sessionDate: 'date|string',
      sourceType: 'string',
      sessionStatus: 'PENDING_REVIEW|APPROVED|ARCHIVED|DELETED',
      reviewStatus: 'PENDING|REVIEWED|DISMISSED|null',
      seriesCount: 'number',
      shotCount: 'number',
      totalScore: 'number',
      notes: 'string|null',
      rawImportJson: 'object|null',
      createdAt: 'timestamp',
      updatedAt: 'timestamp',
      approvedAt: 'timestamp|null',
      archivedAt: 'timestamp|null',
    },

    sessionSeries: {
      seriesId: 'string',
      sessionId: 'string',
      seriesCode: 'SR1|SR2|SR3|SR4|SR5|SR6',
      seriesOrder: 'number',
      eventStatus: 'PARTIAL|FINAL',
      seriesTotal: 'number',
      shotValuesCsv: 'string',
      createdAt: 'timestamp',
      updatedAt: 'timestamp',
    },

    sessionShot: {
      shotId: 'string',
      sessionId: 'string',
      seriesId: 'string',
      seriesCode: 'SR1|SR2|SR3|SR4|SR5|SR6',
      shotNumber: 'number',
      score: 'number|string',
      directionCode: 'string|null',
      xValue: 'number|null',
      yValue: 'number|null',
      innerTen: 'boolean|null',
      confidence: 'string|null',
      createdAt: 'timestamp',
    },

    targetSession: {
      targetSessionId: 'string',
      athleteId: 'string',
      athleteName: 'string',
      eventCode: 'string',
      sessionType: 'TRAINING|SIMULATION|COMPETITION',
      modality: 'PISTOL|RIFLE|null',
      targetType: 'string',
      totalShots: 'number',
      zoneLabels: 'string[]',
      zoneCounts: 'number[]',
      recommendedTrainingCode: 'string|null',
      recommendedTrainingLabel: 'string|null',
      sessionStatus: 'PENDING_REVIEW|APPROVED|ARCHIVED|DELETED',
      sourceType: 'string',
      submittedAt: 'timestamp',
      approvedAt: 'timestamp|null',
      archivedAt: 'timestamp|null',
    },

    prescription: {
      prescriptionId: 'string',
      athleteId: 'string',
      athleteName: 'string',
      dayNumber: 'number',
      blockCode: 'string',
      trainingCode: 'string',
      trainingTitle: 'string',
      prescribedByRole: 'string',
      sourceType: 'string',
      createdAt: 'timestamp',
      updatedAt: 'timestamp',
    },

    athleteView: {
      athleteId: 'string',
      athleteName: 'string',
      athleteEmail: 'string|null',
      modality: 'PISTOL|RIFLE|null',
      levelCode: 'string|null',
      hci: 'number|null',
      latestTotal: 'number|null',
      medianTotal: 'number|null',
      sessionsCount: 'number',
      targetSessionsCount: 'number',
      prescriptionsCount: 'number',
      parameters: 'array',
      sessions: 'array',
      prescriptions: 'array',
      updatedAt: 'timestamp',
    },
  },
}
